on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Generate some release notes
        id: notes
        # You have to update this with your branch when developing. 
        #   It doesn't look like you can use env, steps, or github contexts
        #   for a uses:
        uses: daytime-em/release-notes-on-pr@match-labels
        with:
          pull_number: 12
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: fixes,breaking
      - name: Just echo something
        run: echo "Anything "
